---
#- name: Update the host
#  sudo: yes
#  apt: update_cache=true

#- name: Upgrade the host packages
#  sudo: yes
#  apt: upgrade=yes

- name: install some usefull packages
  sudo: yes
  apt: name={{item}} state=present
  with_items:
    - cloc
    - curl
    - htop
    - make
    - wget
    - nano
