---

# On Ubuntu target: add nginx stable repository from PPA and install its signing key.
# On Debian target: adding PPA is not available, so it will fail immediately.
- name: add ppa repository for PHP 5.6
  sudo: yes
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present
  register: ppa_added

- name: update package
  sudo: yes
  apt: update_cache=true
  when: ppa_added|changed

- name: install php
  sudo: yes
  apt: name={{item}} state=present
  with_items:
    - php5

- name: setup custom php conf
  template: src=custom_php_conf.ini dest=/etc/php5/custom_php_conf.ini owner=root

- name: add custom php config to apache
  file: src=/etc/php5/custom_php_conf.ini dest=/etc/php5/apache2/conf.d/20-custom_php_conf.ini state=link

- name: add custom php config to cli
  file: src=/etc/php5/custom_php_conf.ini dest=/etc/php5/cli/conf.d/20-custom_php_conf.ini state=link
