---

- name: install zsh
  sudo: yes
  apt: name={{item}} state=present
  with_items:
    - git
    - zsh

# depth=1 to improve speed
- name: git clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest={{user_home}}/.oh-my-zsh
       depth=1

- name: setting permissions to .oh-my-zsh
  sudo: yes
  file: path={{user_home}}/.oh-my-zsh
        owner={{ whoami }}
        group={{ whoami }}
        recurse=yes

- name: deploy .zshrc
  template: src=zshrc.sh
            dest={{user_home}}/.zshrc
            owner={{whoami}}
            backup=yes

- name: set zsh as default shell
  sudo: yes
  user: name={{whoami}}
        shell=/usr/bin/zsh
